git-debimport redhat-cluster_3.1.8-1.2.debian.tar.xz

diff --git a/config/tools/xml/ccs_config_validate.in b/config/tools/xml/ccs_config_validate.in
--- a/config/tools/xml/ccs_config_validate.in
+++ b/config/tools/xml/ccs_config_validate.in
@@ -17,6 +17,15 @@ if [ -z "$COROSYNC_DEFAULT_CONFIG_IFACE" ]; then
 	export COROSYNC_DEFAULT_CONFIG_IFACE=$CONFIG_LOADER:cmanpreconfig
 fi
 
+get_config_version() {
+	local file=$1
+
+	echo "xpath /cluster/@config_version" | \
+		xmllint --shell "$file" | \
+		grep content | \
+	cut -f2 -d=
+}
+
 print_usage() {
 	echo "Usage:"
 	echo ""
@@ -33,11 +42,14 @@ print_usage() {
 	echo "  -l configfile    Validate an alternate config file (load test)"
 	echo ""
 	echo "Advanced options:"
+	echo "  -u               Do not update relaxng schema"
 	echo "  -r               Force validation of runtime config"
 	echo "  -C config_loader Override config plugin loader"
 	echo "  -t tempfile      Force temporay file to tempfile"
 	echo "  -n               Do not remove temporary file"
 	echo "  -o               Overwrite temporary file (dangerous)"
+	echo "  -R version       When validating configuration update, ensure the"
+	echo "                   new config is newer than the specified version."
 }
 
 check_opts() {
@@ -60,6 +72,10 @@ check_opts() {
 		;;
 		-o)
 			overwritetempfile=1
+		;;
+		-R)	
+			shift
+			old_version=$1
 		;;
 		-C)
 			shift
@@ -120,6 +136,9 @@ check_opts() {
 				exit 255
 			fi
 		;;
+		-u)
+			updaterelaxng=0
+		;;
 		esac
 		shift
 	done
@@ -131,7 +150,7 @@ lecho()
 	return 0
 }
 
-opts=$(getopt t:hVnC:f:l:rovq $@)
+opts=$(getopt t:hVnC:f:l:rR:ovqu $@)
 if [ "$?" != 0 ]; then
 	print_usage >&2
 	exit 255
@@ -167,12 +186,48 @@ else
 fi
 lecho "Configuration stored in temporary file"
 
+lecho "Updating relaxng schema"
+if [ "$updaterelaxng" != 0 ]; then
+	updateerr="$(ccs_update_schema 2>&1)"
+	if [ $? != 0 ]; then
+		echo "Unable to update relaxng schema: $updateerr" >&2
+		exit 255
+	fi
+fi
+
+if [ -f /var/lib/cluster/rng_update.lock ]; then
+	echo "Relax-ng schema update in progress" >&2
+	exit 255
+fi
+
+if [ ! -e @SHAREDIR@/cluster.rng ]; then
+	echo "Unable to verify a configuration without relaxng schema" >&2
+	exit 255
+fi
+
 lecho "Validating.."
 
 xmlout=$(xmllint --noout \
 	--relaxng @SHAREDIR@/cluster.rng \
 	$tempfile 2>&1)
 res=$?
+
+if [ -n "$old_version" ] && [ $old_version -ne 0 ] && [ $res -eq 0 ]; then
+	new_version=$(get_config_version $tempfile)
+	if [ -z "$new_version" ]; then
+		[ -z "$quiet" ] && \
+			echo "Error: Unable to determine new config version!" >&2
+		[ -z "$notempfilerm" ] && rm -f $tempfile
+		exit 253
+	fi
+	lecho "Old version: $old_version   New version: $new_version"
+	if [ $new_version -le $old_version ]; then
+		[ -z "$quiet" ] && \
+			echo "Error: Configuration version is older than running config!" >&2
+		[ -z "$notempfilerm" ] && rm -f $tempfile
+		exit 254
+	fi
+fi
 
 if [ -z "$quiet" ] || [ "$res" != "0" ]; then
 	echo "$xmlout" | sed \
